# Generated by Django 5.2.7 on 2026-01-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
